url: http://stefaniuk.co.uk
permalink: /:title

title: Dan Stefaniuk
description: >
  A blog about software development.

email: daniel.stefaniuk@gmail.com
github_username: stefaniuk
linkedin_username: dstefaniuk
stackoverflow_username: 472150
twitter_username: danstefaniuk

timezone: Europe/London
markdown: redcarpet

gems:
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-terminal

sass:
  style: :compressed

exclude:
  - Makefile
  - TODO.md
