url: http://stefaniuk.co.uk
permalink: /:title

title: Daniel Stefaniuk
description: >
  This is my blog about programming.

email: daniel.stefaniuk@gmail.com
github_username: stefaniuk
linkedin_username: dstefaniuk
twitter_username: danstefaniuk

markdown: kramdown

gems:
  - jekyll-last-modified-at
  - jekyll-sitemap

sass:
  style: :compressed

exclude:
  - TODO.md
